<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Version>2.6.0.3</Version>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Company>Goober</Company>
    <Authors>Goober</Authors>
    <PackageReleaseNotes>Исправлено исключение KeyNotFoundException в GetManyAsync</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="6.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Goober.Base\Goober.Base.csproj" />
    <ProjectReference Include="..\Goober.Caching.Abstractions\Goober.Caching.Abstractions.csproj" />
  </ItemGroup>

</Project>
